@extends('layouts.appfront')
@section('content')
    @include('global.front_topnav')
    <div class="wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xl-12">
                    {{ HTML::image('img/UACareer PARTNERSHIP.png', 'UA', array('width'=>'100%')) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card-box">
                            <div class="hiring-list mt-4">
                                <p class="text-center">
                                <h3>Introduction</h3>
                                This page contains the Terms and Conditions that govern your use of the Uacareers.online Website. Please take your time reading this page. Do not use this Website or service if you do not accept the Terms and Conditions stated herein. Uacareers.online reserves the right to change these Terms and Conditions at any time by updating this page. Your use of this Website or access to it indicates your acceptance of these Terms and Conditions.
                                <h3>Recommended Use of the Website</h3>
                                The Website, its assistance, database, and other features are only intended for individuals looking for work, employers or recruiters looking for candidates for work, and schools looking for employment information on their alumni. Users of Uacareers.online agree to use the Website only for lawful purposes within the stated context of Uacareers.online's intended and acceptable use of the Website, which will be interpreted in accordance with normal and customary usage, in a manner most beneficial to all parties.
                                <h3>Job Finder</h3>
                                Uacareers.online shall immediately grants you a limited, terminable, non-exclusive right to access and use the Website solely for the purpose of searching for employment opportunities. In response to any job advertisement, you may send your resume to Uacareers.online via the Website. This license allows you to view and download a single copy of the material on the Website for personal, noncommercial use only. In this case, your resumé will remain active on the Website for a predetermined period of time and, unless you choose to delete it, will be stored in the Uacareers.online Database at your own risk. Uacareers.online also reserves the right to make changes to your resumé at its discretion.You accept and consent to the practice of Uacareers.online charging Employers a fee for access to the Website, Database, and your resumé and details. You also acknowledge that you have no claim to any fees collected by Uacareers.online. Furthermore, you acknowledge and agree to the practice of Uacareers.online of providing free access to your school or alma mater to the Website, Database, and your resumé and details. You also agree that Uacareers.online and its affiliated companies may use your personal information for marketing purposes.
                                You assert to be exclusively accountable for the content of any Document you post to the Website, as well as the consequences of such posting. Your use of the Website is a privilege. Uacareers.online reserves the right, in its sole discretion, to suspend or terminate that privilege at any time for any reason.
                                As asserted in the policy, someone information as a job seeker will be released to employers when you apply for a job or when your resumé is purchased when you meet the requirements for the job. Please be aware that based on your application and/or interview, some employers may conduct a pre-employment background check on you. By applying for the position, you are deemed to have consented to a pre-employment background check without further notice or consent. You agree to our privacy policy by using this site and providing information as a registered user.
                                Uacareers.online will not be held responsible or liable in any way if any Employer or School, whether in the Philippines or elsewhere, uses your personal data for any purpose other than obtaining potential employees or learning about your employment profile. You agree that any personal information you provide to Employers, Schools, or other users is entirely at your own risk.
                                <h3>Employers</h3>
                                Uacareers.online shall immediately guarantees you a limited, revocable, non-exclusive license to access and use the Website and Resumé Database solely for the purpose of seeking candidates for employment. Following agreement of the predetermined service, you will be entitled to use the Website to advertise job vacancies and/or create your own web page on the Website for a predetermined period. This license allows you to view and download a single copy of the material on the Website for your personal use directly related to using the Website for the purpose of searching and recruiting job candidates. Without the express written permission of Uacareers.online, you might not always offload, transfer, or assign any products or services or your rights to any products or services (including access to the Resumé Database) provided by Uacareers.online to any third party. You agree that you are solely responsible for the content of any advertisement/web page you post to the Website, as well as the consequences of such posting. If Uacareers.online determines that you are in breach of any of these Terms and Conditions, Uacareers.online reserves the right to edit any advertisement or web page as it sees fit, or to suspend or terminate your access and use entirely.
                                Uacareers.online is allowed to change the Service Fee or impose new charges or fees as it sees fit.If an Employer fails to pay the Service Fee or any other fees or charges owed to Uacareers.online, Uacareers.online reserves the right to suspend or terminate the Employer's web page or advertisement without prior notice and without prejudice to all other rights or recourse.
                                <h3>Schools</h3>
                                Uacareers.online henceforth guarantees you a limited, revocable, non-exclusive license to access and use the Website and Resumé Database solely for internal purposes of gaining insight into the employment status of your graduates. Following agreement of the predetermined service, you will be entitled to use the Website to create your own web page on the Website for a predetermined period. This permits you to view the material on the Website solely for your personal use in connection with using the Website to look up on the employment profiles of your alumni.
                                <h3>Posting</h3>
                                Your web pages must not represent: copyrighted material (unless you own the copyright or have permission from the owner to post the copyrighted material); personal information (unless you own them or have permission from the owner to post them); material that infringes or misappropriates any other intellectual property rights, or violates the privacy or publicity rights of others; or anything that is discriminatory, sexually explicit, obscene, libelous, defamatory, threatening, harassing or link to material that sexually, violently, or otherwise exploits people, or solicits personal information from anyone; material that provides instructional information about illegal activities or other activities prohibited by these Terms and Conditions, including, but not limited to, making or purchasing illegal weapons, violating someone's privacy, providing or creating computer viruses, or pirating any media, or soliciting passwords or personal identifying information from anyone.
                                <h3>Conduct</h3>
                                You may not respond to other Users' postings in any way or for any reason other than what is expected (i.e., to apply for the job or to initiate further discussion with the candidate). Communications from our competitors soliciting the employer's business are prohibited.

                                Inappropriate postings or behavior should be reported to violations@Uacareers.online.

                                If Uacareers.online believes that you have misled Uacareers.online about your business practices and/or services, or that you have purchased services that do not accurately represent your business, Uacareers.online reserves the right to terminate this agreement.

                                Uacareers.online is not required to monitor its Users' behavior, but it may investigate and respond when violations are reported.
                                <h3>Security</h3>
                                Desist from violating or attempting to violate the Website's security, including, but not limited to:
                                •	accessing data that is not intended for such User or logging into a server or account to which the User is not authorized;
                                •	attempting to probe, scan, or test a system's or network's vulnerability, or breaching security or authentication measures without proper authorization;
                                •	attempting to disrupt service to any User, host, or network, including, but not limited to, sending a virus to the Website, overloading, "flooding," "mailbombing," or "crashing";
                                •	sending unsolicited email, including product or service promotions and/or advertising
                                •	forging any TCP/IP packet header or part of a TCP/IP packet header in any email or newsgroup posting;
                                •	taking any action that places an unreasonable or disproportionately large load on the infrastructure of Uacareers.online;
                                •	Using or attempting to use any engine, software, tool, agent, or other device or mechanism (including without limitation browsers, spiders, robots, avatars, or intelligent agents) to navigate or searchUacareers.online other than the search engine and search agents available fromUacareers.online on such Website and other than generally available third party web browsers (e.g., Netscape Navigator, Microsoft Explorer, Firfox) to navigate or search Uacareers.online
                                •	attempting to decipher, decompile, disassemble, or reverse engineer any software comprising or comprising a component of any Uacareers.online;
                                System or network security violations may result in civil or criminal liability. Uacareers.online will investigate occurrences that may involve such violations and may involve and cooperate with law enforcement authorities in prosecuting Users involved in such violations.


                                <h3>Intellectual Property</h3>
                                The portions of this Website, including text, graphics, images, and other materials (the Material), are copyright protected. You may not sell or modify the Material, nor may you reproduce, display, publicly perform, distribute, or otherwise use it for any public or commercial purpose in connection with products or services that are not those of Uacareers.online, or in any other way that infringes Uacareers.online intellectual property rights. This includes copying or modifying the HTML code used to generate the Website's web pages. It is prohibited to use the Material on any other website or in a networked computer environment for any purpose.
                                <h3>Provisos and Liability Limitations for Uacareers.online</h3>
                                <h3>Allocation of Responsibility</h3>
                                Uacareers.online accepts no responsibility for User-posted content or for the activities, omissions, or other conduct of Users. Uacareers.online serves as a portal for the online distribution and publication of User-submitted information and has no obligation to screen communications or information in advance and is not responsible for screening or monitoring User-posted content. If Uacareers.online is notified by a User of content that allegedly violates this agreement, Uacareers.online may investigate the allegation and decide in good faith and sole discretion whether to remove or request the removal of such content. Uacareers.online has no liability or responsibility to Users for the performance or nonperformance of such activities. In its sole discretion, Uacareers.online may take any action with respect to User-submitted information that it deems necessary or appropriate.
                                <h3>No Guaranty of Results</h3>
                                Uacareers.online does not constitute an employment agency or a recruiting firm, and makes no representations or guarantees about the Website's effectiveness or timeliness in meeting the employment objectives of Users. Uacareers.online does not guarantee that Documents posted by Users will result in candidates being hired or positions being filled, and is not responsible for any employment decisions made by any User, for whatever reason.
                                <h3>Disclaimers of Warranties</h3>
                                Without limiting the foregoing, Uacareers.online's aggregate liability to any user for all claims arising from their use of Uacareers.online services shall be limited to the amount of the existing Service Fee subscribed to and paid for by the User (if any) and in effect at the time.
                                In no event shall Uacareers.online be liable for any damages, loss, or expense, including without limitation, direct, special, or consequential damage, or economic loss, arising from or in connection with:
                                •	A certain entry, use, or inability to access or use this website, as well as any reliance on the materials and/or information on the website.
                                •	Any failure of a system, server, or connection, error, omission, interruption, transmission delay, or computer virus.
                                •	A certain use or access to any other website that is linked to this one.
                                The Website serves as a venue for employers to post job openings and candidates to post resumes, but it does not screen or censor the listings. Uacareers.online is not a party to the transaction between Employers and Candidates. As a result, Uacareers.online has no control over the quality, safety, or legality of the jobs or resumés posted, the truth or accuracy of the listings, Employers' ability to offer job opportunities to candidates, candidates' ability to fill job openings, or any User Content, and makes no representations about any jobs, resumés, or User Content on the Website. Uacareers.online is not an employer in relation to your use of the Website, and Uacareers.online is not liable for any employment decisions made by any entity posting jobs on the Website, for whatever reason.
                                <h3>Service Payment Upon Termination of Service Agreement</h3>
                                If you terminate a Service Agreement in which these Terms and Conditions have been incorporated by reference at any time during the term of this Agreement, including termination due to Uacareers.online's breach of this Agreement or the Service Agreement, Uacareers.online reserves the right to receive all payments from you for the Services used by you up to termination, as well as fifty percent (50%) of the remaining unused portion of the Service Agreement
                                <h3>Links to other Sites</h3>
                                Links to third-party websites may be found on uacareers.online. These are provided solely for your convenience and do not constitute an endorsement of the content on such third-party websites by Uacareers.online. You access any linked third-party websites entirely at your own risk. Uacareers.online is not responsible for the content of any third-party websites linked to its Website, and makes no representations or warranties about the content or accuracy of materials on such third-party websites.
                                <h3>Amendments to this Agreement and Site Changes</h3>
                                Uacareers.online reserves the right to change this Agreement at any time by updating this page. Changes will become effective as of the date they are posted on the Website (or as otherwise stated in the any notice of such changes). Any use of the Website constitutes your acceptance of the then-current Terms and Conditions (including any Exhibits thereto). You may not use the Website if you find the Terms and Conditions unacceptable at any time. Uacareers.online expressly rejects any new or different terms supplied by you unless Uacareers.online expressly agrees to them in a signed writing specifically including those new or different terms. Uacareers.online reserves the right to change the Website at any time.
                                <h3>Indemnity</h3>
                                Most users agree to indemnify and hold Uacareers.online, its officers, directors, employees, representatives, and agents harmless from and against any claims, actions, demands, losses, or damages arising from or resulting from their use of Uacareers.online or their violation of the terms of this Agreement. Uacareers.online will make reasonable efforts to provide the relevant user with prompt notice of any such claim, suit, or proceeding.
                                If the courts hold Uacareers.online liable for losses and damages, total liability shall not exceed double the Service Fee as set forth in the Service Agreement with the Employer. Furthermore, any action arising from these services cannot be brought against Uacareers.online after two years from the occurrence of the cause of action.


                                <h3>Own Risk</h3>
                                Users use Uacareers.online and any other websites linked to it entirely at their own risk. All Users are solely responsible for their own communications and the consequences of their actions. Uacareers.online does not represent or guarantee the truthfulness, accuracy, or reliability of any communications posted by other Users, nor does it endorse any of their opinions. Users relying on material posted by other Users do so at their own risk. Uacareers.online reserves the right to expel any User and prevent their further access to Uacareers.online at any time for breaching this Agreement or violating the law, as well as the right to remove any material that is abusive, illegal, or disruptive.
                                <h3>User Policies</h3>
                                <h3>User Information</h3>
                                Once you sign up with the Website, you will be asked to submit certain information to Uacareers.online, including, but not limited to, a valid email address (your "Information"). In addition to the terms and conditions set forth in any privacy policy on this Website, you understand and agree that Uacareers.online may disclose certain aggregate information contained in your registration application to third parties on an anonymous basis. Uacareers.online will not disclose your name, address, email address, or phone number to any third party without your prior consent, except to the extent necessary or appropriate to comply with applicable laws, rules, or regulations, or in legal proceedings where such information is relevant. Uacareers.online holds the right to offer you third-party services and products based on your registration preferences and at any time thereafter; such offers may be made by Uacareers.online or by third parties. For more information on your information, please see the Uacareers.online Privacy Policy.
                                <h3>User Submissions</h3>
                                You are solely responsible as a User for your Account information, content, messages, or other information ("User Content") that you submit, publish, or display on the Website or transmit to other users. By submitting User Content to any public area of the Website, including message boards, forums, contests, and chat rooms, you grant Uacareers.online and its affiliates a royalty-free, perpetual, irrevocable, non-exclusive right (including any moral rights) and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, communicate to the public, perform, and display the User Content (in whole or in part) worldwide and/or to incorporate the User Content.
                                <h3>Registration and Password</h3>
                                You are solely responsible for keeping your account access information and password secure. You are responsible for all uses of your registration, whether authorized by you or not. You are not authorized to share your password or other account access information with any other party, either temporarily or permanently, and failure to do so may result in the deactivation of your Uacareers.online account and Uacareers.online Services. You agree to notify Uacareers.online immediately of any unauthorized use of your registration or password.



                                <h3>Express Consent and Acknowledgement</h3>
                                When you submit your resumé for storage in our resumé database, you acknowledge, consent, and agree that your resumé is automatically searchable by employers, recruiters, hiring managers, headhunters, and human resource professionals (the "Employers") who pay for access to our resumé database. Uacareers.online is not liable for the use of resumes by Employers who accessed your resume while it was in our database. You agree that when your resume is displayed in our database, personal information contained within it (such as your email address) may be collected and used by parties other than the Employers. This may lead to unsolicited messages from third parties, for which Uacareers.online is not liable. Uacareers.online will make every effort to limit Employers' access to our resumé database, but cannot guarantee that other parties will not gain access to this database. You may remove your resumé from the Website at any time, but Employers who have gained access to our database may have kept a copy in their own files or databases. In these cases, Uacareers.online is not responsible for the retention, use, or privacy of resumés or profiles.
                                <h3>Notification of Alleged Copyright Violation</h3>
                                If you accept your copyrighted work has been uploaded, posted, or copied to Uacareers.online and is accessible on such Website in a way that constitutes copyright infringement, please contact us at customerservice@Uacareers.online and provide the following information:
                                •	The physical or electronic signature of the copyright owner or a person authorized to act on behalf of the owner;
                                •	A description of the allegedly infringed copyrighted work, as well as a description of the allegedly infringing activity;
                                •	Identification of the URL or other specific location on this Website where the material or activity you claim to be infringing is located or is taking place; you must include sufficient information to allow us to locate the material or activity.
                                •	Your name, address, phone number, and email address, if you have one; The physical or electronic signature of the copyright owner or a person authorized to act on behalf of the owner;
                                •	A description of the allegedly infringed copyrighted work, as well as a description of the allegedly infringing activity;
                                •	Identification of the URL or other specific location on this Website where the material or activity you claim to be infringing is located or is taking place; you must include sufficient information to allow us to locate the material or activity.
                                •	name, address, mobile number, and email address, if you have one;
                                •	A assertion from you stating that you have a good faith belief that the use of the copyrighted work on the Website in the manner you are complaining about is not authorized by the copyright owner, any agent of the copyright owner, or the law; and
                                •	A comment made under penalty of perjury by you that the information in your notice is correct and that you are either the copyright owner or have authority to act on behalf of the copyright owner.


                                <h3>Policy on the Termination of Users and Account Holders Who Repeatedly Infringe Others' Copyright or Other Intellectual Property Rights</h3>
                                Uacareers.online honors others' intellectual property and asks its users, account holders, and content partners to do the same. Unauthorized reproduction, copying, distribution, modification, public display, or public performance of copyrighted works constitutes an infringement of the rights of the copyright holders. As a condition of using Uacareers.online, you agree not to infringe on the intellectual property rights of others in any way.Uacareers.online will terminate any account holders' accounts and block access to the Website of any User who repeatedly infringes others' copyrights or other intellectual property rights.
                                <h3>Questions and Notice</h3>
                                Questions about using the Website should be directed to Feedback. Notices shall be sent to the address listed on the Website for Uacareers.online and to the address submitted by you or to such other address as Uacareers.online reasonably determines is an appropriate address for you.
                                <h3>No Resale or Unauthorized Commercial Use</h3>
                                You concede not to buy back any Material or information obtained from the Website, to assign your rights or obligations under these Terms and Conditions, or to use Uacareers.online for any unauthorized commercial purpose.
                                <h3>Dismissal and Term</h3>
                                These Conditions and Policies will continue to apply to you as long as you use the Website at any level. Uacareers.online. reserves the right, at its sole discretion, to pursue all legal remedies, including but not limited to the deletion of your User Content from the Website and immediate termination of your registration with or ability to access the Website and/or any other services provided to you by Uacareers.online, in the event that you breach these Terms and Conditions or if Uacareers.online is unable to verify or authenticate any information you submit to the Website. Certain provisions of these Terms and Conditions will remain in effect even if you no longer use the Website.




                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
